### PR TITLE
feat(#9): Copper debugging

### PR DESCRIPTION
**Pull request by prb28**
Work done to debug the copper, adding thread/multiprocess management in the protocol.

### CODE REVIEW

**Comment by emoon** [comment]
wow! this is awesome :) I really don't have time to review everything right now but I will accept it as is. I plan to get back to helping out adding more features to this soon.

**Comment by emoon** [comment]
Also there seems to be a conflict with the `remote_debug.cpp` file. Do you think you can resolve that?

**Comment by prb28** [comment]
Yep! I'll fix that.

**Comment by prb28** [comment]
I think I need the write access to make the merge, is there a way to do it without ?

**Comment by emoon** [comment]
not sure, I added you to the repo now

**Comment by prb28** [comment]
Thanks, I did the merge, just kept my modifications.
I hope it's not too far from your coding standards.
I pull the last trigger to merge...

**Comment by prb28** [comment]
Before pulling it:
it certainly will beak the communications between your asm debugger and fs-uae, you may want to wait and test it before the merge.

**Comment by emoon** [comment]
it should be fine. I may do pass over the code when I have some time. Thanks for the great work :) please go ahead and merge!

**Comment by prb28** [comment]
ok thanks

**Pull request merged**
